### ISSUE TITLE
Create single pet view function

### ISSUE THREAD

**Issue by lenora4321** [CSI-280/clubtwister#15]
We will eventually need a page for viewing a single pet, like if you click on it and want to view the details.  Right now, we should work on getting a function to just get one animal and grab all relevant details so that we can work on creating s display for them later.

**Comment by Gumbachi** [comment]
I can work on this but my knowledge of HTML & CSS isn't great so it might be ugly.

**Comment by lenora4321** [comment]
In implementation, this will probably look like a link that takes you to a new SinglePet html page with an accompanying value holding the pet's ID.  From there, it should be fairly straightforward to get the data and display it about the pet, but transferring the ID over might be hard.  Either do this using session storage, or with a function that changes the window.location value
